graph TB
    START[ ]
END[ ]
style START opacity:0
style END opacity:0

A[ ]
style A opacity:0
B[Vertex-Verarbeitung]
C[Rasterisierung]
D[Fragmment-Verarbeitung]
E[Blending]

START ~~~ A
A -->|Geometrie| B
B -->|verarbeitete Geometrie| C
C -->|Fragmente| D
D -->|verarbeitete Fragmente| E
E -->|Pixel| END
